-- Run as a role permitted to create these objects. Change names if your trial restricts roles.
CREATE WAREHOUSE IF NOT EXISTS SUPPLYCHAIN_HACK_WH
  WAREHOUSE_SIZE = 'X-SMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE DATABASE IF NOT EXISTS SUPPLYCHAIN_ATLAS;
CREATE SCHEMA IF NOT EXISTS SUPPLYCHAIN_ATLAS.CORE;
USE WAREHOUSE SUPPLYCHAIN_HACK_WH;
USE DATABASE SUPPLYCHAIN_ATLAS;
USE SCHEMA CORE;

