USE DATABASE SUPPLYCHAIN_ATLAS;
USE SCHEMA CORE;

CREATE OR REPLACE TABLE SUPPLIERS (
  SUPPLIER_ID STRING, SUPPLIER_NAME STRING, COUNTRY STRING, RISK_TIER STRING, ON_TIME_RATE NUMBER(5,2)
);
CREATE OR REPLACE TABLE PLANTS (
  PLANT_ID STRING, PLANT_NAME STRING, COUNTRY STRING, CRITICALITY STRING
);
CREATE OR REPLACE TABLE PARTS (
  PART_ID STRING, PART_NAME STRING, CATEGORY STRING, LEAD_TIME_DAYS INTEGER, UNIT_COST NUMBER(12,2)
);
CREATE OR REPLACE TABLE PURCHASE_ORDERS (
  PO_ID STRING, SUPPLIER_ID STRING, PART_ID STRING, PLANT_ID STRING, QUANTITY INTEGER,
  PROMISED_DATE DATE, STATUS STRING
);
CREATE OR REPLACE TABLE SHIPMENTS (
  SHIPMENT_ID STRING, PO_ID STRING, CARRIER STRING, ORIGIN STRING, DESTINATION STRING,
  ETA DATE, ACTUAL_OR_FORECAST_DELAY_DAYS INTEGER, STATUS STRING, LAST_EVENT_AT TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE CUSTOMER_ORDERS (
  ORDER_ID STRING, PART_ID STRING, PLANT_ID STRING, CUSTOMER_SEGMENT STRING,
  REVENUE_AT_RISK NUMBER(14,2), REQUIRED_DATE DATE, STATUS STRING
);
CREATE OR REPLACE TABLE SENSOR_EVENTS (
  EVENT_ID STRING, SHIPMENT_ID STRING, EVENT_AT TIMESTAMP_NTZ, TEMPERATURE_C NUMBER(8,2),
  SHOCK_G NUMBER(8,2), GPS_STATUS STRING
);

CREATE OR REPLACE TABLE SHIPMENT_RISK (
  SHIPMENT_ID STRING, RISK_SCORE NUMBER(6,2), RISK_LEVEL STRING, DELAY_FACTOR NUMBER(8,2),
  SENSOR_FACTOR NUMBER(8,2), SUPPLIER_FACTOR NUMBER(8,2), CALCULATED_AT TIMESTAMP_NTZ
);

CREATE OR REPLACE VIEW V_ORDER_IMPACT AS
SELECT s.SHIPMENT_ID, s.PO_ID, s.STATUS AS SHIPMENT_STATUS, s.ETA,
       r.RISK_SCORE, r.RISK_LEVEL, po.PART_ID, po.PLANT_ID,
       co.ORDER_ID, co.CUSTOMER_SEGMENT, co.REVENUE_AT_RISK, co.REQUIRED_DATE
FROM SHIPMENTS s
JOIN SHIPMENT_RISK r ON r.SHIPMENT_ID = s.SHIPMENT_ID
JOIN PURCHASE_ORDERS po ON po.PO_ID = s.PO_ID
LEFT JOIN CUSTOMER_ORDERS co ON co.PART_ID = po.PART_ID AND co.PLANT_ID = po.PLANT_ID;

