USE DATABASE SUPPLYCHAIN_ATLAS;
USE SCHEMA CORE;

-- A transparent, inspectable metric surface for the demo and a future semantic model.
CREATE OR REPLACE VIEW V_CONTROL_TOWER AS
SELECT i.*, p.PART_NAME, pl.PLANT_NAME, sup.SUPPLIER_NAME,
       SUM(COALESCE(i.REVENUE_AT_RISK, 0)) OVER (PARTITION BY i.SHIPMENT_ID) AS TOTAL_REVENUE_AT_RISK
FROM V_ORDER_IMPACT i
JOIN PURCHASE_ORDERS po ON po.PO_ID = i.PO_ID
JOIN PARTS p ON p.PART_ID = i.PART_ID
JOIN PLANTS pl ON pl.PLANT_ID = i.PLANT_ID
JOIN SUPPLIERS sup ON sup.SUPPLIER_ID = po.SUPPLIER_ID;

-- Demo quality checks. Any nonzero result should block the presentation data refresh.
SELECT 'orphan_shipments' AS CHECK_NAME, COUNT(*) AS FAILED_ROWS
FROM SHIPMENTS s LEFT JOIN PURCHASE_ORDERS p ON s.PO_ID = p.PO_ID WHERE p.PO_ID IS NULL
UNION ALL
SELECT 'invalid_risk_scores', COUNT(*) FROM SHIPMENT_RISK WHERE RISK_SCORE < 0 OR RISK_SCORE > 100;

