-- Reproducible live showcase seed for the Snowflake-native Streamlit demo.
USE DATABASE SUPPLYCHAIN_ATLAS;
USE SCHEMA CORE;

INSERT INTO PURCHASE_ORDERS
SELECT 'PO-DEMO-' || LPAD(SEQ4()+1,3,'0'),
       IFF(MOD(SEQ4(),3)=0,'SUP-001',IFF(MOD(SEQ4(),3)=1,'SUP-002','SUP-003')),
       'PRT-00' || (MOD(SEQ4(),3)+1), 'PLT-0' || (MOD(SEQ4(),2)+1),
       50 + MOD(SEQ4()*17,450), DATEADD(day,MOD(SEQ4(),14)+3,CURRENT_DATE()), 'OPEN'
FROM TABLE(GENERATOR(ROWCOUNT=>30));

INSERT INTO SHIPMENTS
SELECT 'SHP-DEMO-' || LPAD(SEQ4()+1,3,'0'), 'PO-DEMO-' || LPAD(SEQ4()+1,3,'0'),
       IFF(MOD(SEQ4(),3)=0,'Atlas Freight',IFF(MOD(SEQ4(),3)=1,'BlueLine Logistics','Nova Cargo')),
       'Singapore','Bengaluru',DATEADD(day,MOD(SEQ4(),12)+1,CURRENT_DATE()),
       IFF(MOD(SEQ4(),7)=0,8,IFF(MOD(SEQ4(),4)=0,4,MOD(SEQ4(),3))),
       IFF(MOD(SEQ4(),4)=0,'DELAYED','IN_TRANSIT'),CURRENT_TIMESTAMP()
FROM TABLE(GENERATOR(ROWCOUNT=>30));

INSERT INTO CUSTOMER_ORDERS
SELECT 'ORD-DEMO-' || LPAD(SEQ4()+1,3,'0'), 'PRT-00' || (MOD(SEQ4(),3)+1),
       'PLT-0' || (MOD(SEQ4(),2)+1),IFF(MOD(SEQ4(),3)=0,'Enterprise',IFF(MOD(SEQ4(),3)=1,'OEM','Strategic')),
       25000+MOD(SEQ4()*23000,180000),DATEADD(day,MOD(SEQ4(),20)+4,CURRENT_DATE()),'OPEN'
FROM TABLE(GENERATOR(ROWCOUNT=>60));

INSERT INTO SENSOR_EVENTS
SELECT 'EVT-DEMO-' || LPAD(SEQ4()+1,3,'0'),'SHP-DEMO-' || LPAD(SEQ4()+1,3,'0'),CURRENT_TIMESTAMP(),
       IFF(MOD(SEQ4(),5)=0,39,24+MOD(SEQ4(),8)),IFF(MOD(SEQ4(),6)=0,3.1,0.4+MOD(SEQ4(),10)/10),'TRACKED'
FROM TABLE(GENERATOR(ROWCOUNT=>30));

INSERT INTO SHIPMENT_RISK
SELECT s.SHIPMENT_ID,
  CASE WHEN s.ACTUAL_OR_FORECAST_DELAY_DAYS>=7 THEN 45 WHEN s.ACTUAL_OR_FORECAST_DELAY_DAYS>=3 THEN 25 ELSE 5 END +
  CASE WHEN e.TEMPERATURE_C>35 OR e.SHOCK_G>2 THEN 25 ELSE 0 END +
  CASE WHEN sup.RISK_TIER='HIGH' THEN 25 WHEN sup.RISK_TIER='MEDIUM' THEN 12 ELSE 3 END,
  CASE WHEN (CASE WHEN s.ACTUAL_OR_FORECAST_DELAY_DAYS>=7 THEN 45 WHEN s.ACTUAL_OR_FORECAST_DELAY_DAYS>=3 THEN 25 ELSE 5 END+CASE WHEN e.TEMPERATURE_C>35 OR e.SHOCK_G>2 THEN 25 ELSE 0 END+CASE WHEN sup.RISK_TIER='HIGH' THEN 25 WHEN sup.RISK_TIER='MEDIUM' THEN 12 ELSE 3 END)>=70 THEN 'CRITICAL' WHEN (CASE WHEN s.ACTUAL_OR_FORECAST_DELAY_DAYS>=7 THEN 45 WHEN s.ACTUAL_OR_FORECAST_DELAY_DAYS>=3 THEN 25 ELSE 5 END+CASE WHEN e.TEMPERATURE_C>35 OR e.SHOCK_G>2 THEN 25 ELSE 0 END+CASE WHEN sup.RISK_TIER='HIGH' THEN 25 WHEN sup.RISK_TIER='MEDIUM' THEN 12 ELSE 3 END)>=40 THEN 'HIGH' ELSE 'WATCH' END,
  0,0,0,CURRENT_TIMESTAMP()
FROM SHIPMENTS s JOIN PURCHASE_ORDERS po ON s.PO_ID=po.PO_ID JOIN SUPPLIERS sup ON po.SUPPLIER_ID=sup.SUPPLIER_ID JOIN SENSOR_EVENTS e ON e.SHIPMENT_ID=s.SHIPMENT_ID
WHERE s.SHIPMENT_ID LIKE 'SHP-DEMO-%';